version: '3.7'

services:
  db:
    hostname: postgres
    image: postgres
    restart: on-failure
    ports:
      - "5433:5432"
    env_file:
      - ./bot/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - bot/.env
    depends_on:
      - db